import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Workshop Division Staff",
    company: "Polytechnic Computer Club (PCC)",
    logo: "/images/careers/logo-pcc.png",
    location: "Semarang, Indonesia 🇮🇩",
    location_type: "Hybrid",
    type: "Organization",
    start_date: "2025-05",
    end_date: null,
    industry: "Technology Community",
    link: "https://ukmpcc.org/",
    responsibilities: [
      "Coordinated UI/UX training sessions and design workshops.",
      "Served as trainer and mentor for UI/UX fundamentals and Figma prototyping.",
      "Assisted internal teams in understanding user flows and improving usability.",
    ],
    responsibilities_id: [
      "Mengoordinasikan sesi pelatihan UI/UX dan workshop desain.",
      "Menjadi pengajar dan mentor untuk materi dasar UI/UX dan pembuatan prototipe di Figma.",
      "Membantu tim internal dalam memahami alur pengguna dan meningkatkan kegunaan aplikasi.",
    ],
    isShow: true,
  },
  {
    position: "Multimedia Department Staff",
    company: "Polytechnic Computer Club (PCC)",
    logo: "/images/careers/logo-pcc.png",
    location: "Semarang, Indonesia 🇮🇩",
    location_type: "Hybrid",
    type: "Organization",
    start_date: "2024-05",
    end_date: "2025-08",
    industry: "Technology Community",
    link: "https://ukmpcc.org/",
    responsibilities: [
      "Designed posters, dashboards, and event graphics.",
      "Collaborated across departments to maintain visual consistency.",
    ],
    responsibilities_id: [
      "Mendesain poster, dasbor, dan grafis untuk keperluan acara.",
      "Berkolaborasi lintas departemen untuk menjaga konsistensi visual desain.",
    ],
    isShow: true,
  },
  {
    position: "Creative Intern",
    company: "Up Radio Semarang",
    logo: "/images/careers/logo-upradio.webp",
    location: "Semarang, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2022-04",
    end_date: "2022-06",
    industry: "Broadcasting",
    link: "https://upradio.id",
    responsibilities: [
      "Designed promotional posters and video content for social media.",
      "Managed radio playlists and assisted on-air broadcasting.",
      "Supported marketing campaigns and audience engagement.",
    ],
    responsibilities_id: [
      "Mendesain poster promosi dan konten video untuk media sosial.",
      "Mengelola playlist radio dan membantu penyiaran siaran langsung (on-air).",
      "Mendukung jalannya kampanye pemasaran dan interaksi dengan audiens.",
    ],
    isShow: true,
  },
  {
    position: "Graphic Designer & Customer Service Intern",
    company: "CV Sumber Bahagia Printing",
    logo: "/images/careers/logo-sumber.jpg",
    location: "Semarang, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2022-01",
    end_date: "2022-04",
    industry: "Printing & Advertising",
    link: "https://www.instagram.com/sumberbahagiaprinting/",
    responsibilities: [
      "Designed brochures, banners, business cards, and printed media.",
      "Communicated directly with clients to gather design requirements.",
      "Coordinated with production team and issued work orders (SPK).",
    ],
    responsibilities_id: [
      "Mendesain brosur, spanduk, kartu nama, dan berbagai media cetak.",
      "Berkomunikasi langsung dengan klien untuk mengumpulkan kebutuhan desain.",
      "Berkoordinasi dengan tim produksi dan menerbitkan Surat Perintah Kerja (SPK).",
    ],
    isShow: true,
  },
];
