import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Workshop Division Staff",
    company: "Polytechnic Computer Club (PCC)",
    logo: "/images/careers/pcc.png",
    location: "Semarang, Indonesia 🇮🇩",
    location_type: "Hybrid",
    type: "Organization",
    start_date: "2025-05",
    end_date: null,
    industry: "Technology Community",
    link: "https://pccpolines.com",
    responsibilities: [
      "Coordinated UI/UX training sessions and design workshops.",
      "Served as trainer and mentor for UI/UX fundamentals and Figma prototyping.",
      "Assisted internal teams in understanding user flows and improving usability.",
    ],
    isShow: true,
  },
  {
    position: "Multimedia Department Staff",
    company: "Polytechnic Computer Club (PCC)",
    logo: "/images/careers/pcc.png",
    location: "Semarang, Indonesia 🇮🇩",
    location_type: "Hybrid",
    type: "Organization",
    start_date: "2024-05",
    end_date: "2025-08",
    industry: "Technology Community",
    link: "https://pccpolines.com",
    responsibilities: [
      "Designed posters, dashboards, and event graphics.",
      "Collaborated across departments to maintain visual consistency.",
    ],
    isShow: true,
  },
  {
    position: "Creative Intern",
    company: "Up Radio Semarang",
    logo: "/images/careers/upradio.png",
    location: "Semarang, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2022-04",
    end_date: "2022-06",
    industry: "Broadcasting",
    link: "https://upradio.id",
    responsibilities: [
      "Designed promotional posters and video content for social media.",
      "Managed radio playlists and assisted on-air broadcasting.",
      "Supported marketing campaigns and audience engagement.",
    ],
    isShow: true,
  },
  {
    position: "Graphic Designer & Customer Service Intern",
    company: "CV Sumber Bahagia Printing",
    logo: "/images/careers/sumber-bahagia.png",
    location: "Semarang, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2022-01",
    end_date: "2022-04",
    industry: "Printing & Advertising",
    link: "",
    responsibilities: [
      "Designed brochures, banners, business cards, and printed media.",
      "Communicated directly with clients to gather design requirements.",
      "Coordinated with production team and issued work orders (SPK).",
    ],
    isShow: true,
  },
];
